[package]
name = "pyrev_pyc"
version = "1.0.12"
edition = "2021"

[dependencies]


[dependencies.pyrev_core]
path = "../pyrev_core"

[dependencies.pyrev_app]
path = "../pyrev_app"

[dependencies.pyrev_pyc_macro]
path = "../pyrev_pyc_macro"